; 这里放你自己新增的分流规则。
; 写法参考：
; ruleset= 应用名,[]GEOSITE,规则名
; ruleset= 应用名,clash-domain:https://example.com/domain.yaml,86400
; ruleset= 应用名,clash-classic:https://example.com/classical.yaml,86400
; 示例：如果以后想单独管理 Discord，可以取消下面这一行注释
; ruleset= Discord,[]GEOSITE,discord
; 示例：如果某个网站没有 GEOSITE，可自己维护一个 yaml
; ruleset= MySite,clash-domain:https://raw.githubusercontent.com/Bloomberg-zhong/openclash-rules/main/rules/mysite.yaml,86400
; 你的自定义规则
ruleset=DIRECT,clash-domain:https://raw.githubusercontent.com/Bloomberg-zhong/openclash-rules/main/rules/direct.yaml,86400
ruleset=访问新加坡,clash-domain:https://raw.githubusercontent.com/Bloomberg-zhong/openclash-rules/main/rules/singapore.yaml,86400

; ===== 以下为本地NAS自定义规则 =====
; 本地NAS自定义直连规则（随时编辑，1小时自动更新）
ruleset=DIRECT,clash-classic:http://192.168.100.110:8801/d/openclash-rules/my_custom_direct.yaml?sign=Qty9fMEvc-ZPjXYeWGHv5cAvI2Ow2s4u5xmB9hj9BtE=:0,3600
; 本地NAS自定义代理规则（随时编辑，1小时自动更新）
ruleset=手动选择,clash-classic:http://192.168.100.110:8801/d/openclash-rules/my_custom_proxy.yaml?sign=f2p_fK7SNcLAYbl-EkvHTZxGYKiRX9aRp4JiIbPKBg8=:0,3600
uleset=手动选择,clash-classic:http://192.168.100.110:8801/d/openclash-rules/my_custom_proxy.yaml?sign=f2p_fK7SNcLAYbl-EkvHTZxGYKiRX9aRp4JiIbPKBg8=:0,3600
